name: flutter_video_cast
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  stream_transform: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: it.aesys.flutter_video_cast
        pluginClass: FlutterVideoCastPlugin
      ios:
        pluginClass: FlutterVideoCastPlugin
